### ISSUE TITLE
No effect on Android 6.0

### ISSUE THREAD

**Issue by hackel** [de-live-gdev/XPrivacyAppInfo#1]
This is probably a known issue. I just installed the mod, and the application info screen remains unchanged. It looks like this screen has gotten a bit of a makeover for 6.0, so I understand why it would no longer work. Hope to see it in a future release!

**Comment by de-live-gdev** [comment]
Currently I have no M device, but also as XPosed for M was released for now I'm gonna wait a little bit when it's more stable. 
I'm indeed interested in keeping the mod up for newer Android-versions.

**Comment by hackel** [comment]
Correct, no crash.

**Comment by de-live-gdev** [comment]
@hackel I reworked the module, check if it also shows up on your device.

**Comment by hackel** [comment]
Works brilliantly now!
