### ISSUE TITLE
Version 1.1 won't install.

### ISSUE THREAD

**Issue by BlackDex** [de-live-gdev/XPrivacyAppInfo#2]
When I try to install version 1.1 I get the message "App not installed". Version 1.0 installs just fine.

I have Android 5.1.1.

**Comment by de-live-gdev** [comment]
Uninstall v1.0 first, I used a different keystore for this apk. The first release (1.0 was from debug keystore). Then it should work without aby problems

**Comment by BlackDex** [comment]
Ah, that's the solution alright!
The.
